### PR TITLE
fix: engine instances numbers above 1 show as starboard

### LINKED ISSUE #143: Engine/Genset Instance Handling
I recently added a Yacht Devices YDEG J1939 to N2K gateway for my generator.  I configured it as instance 2 (instance 0 & 1 cover my mains) - that is confirmed by my Actisense NGT-1 reader (running on a Win PC) connected to the N2K network.  The Actisense reader sees the instance (2), RPM, coolant temperature and runtime.

I have two issues:
1) The genset appears in Signal K as an additional propulsion.starboard engine, only differentiated by the source field,  Being another instance, I would expect something like propulsion.2.xxx
2) Only coolant temp and runtime appear in Signal K (from PGN 127489).  RPM (PGN 127488) do not appear unless I configure the genset gateway as another instance 0 (which greatly confuses the MFD displays).  Attached is a NGT-1 log.
[skserver-raw_2019-02-27T22.log](https://github.com/SignalK/n2k-signalk/files/2915460/skserver-raw_2019-02-27T22.log)

### PR DESCRIPTION
**Pull request by sbender9**
Closes #143

### CODE REVIEW

File: utils.js [hunk 1]
```diff
@@ -1,10 +1,21 @@
...
+  let id = chooseField(n2k, 'Engine Instance', 'Instance')
+  if ( typeof id === 'number' ) {
+    return id
+  } else {
+      return id === 'Single Engine or Dual Engine Port' ? 'port' : 'starboard'
   }
 }
+
+module.exports.chooseField = chooseField
+module.exports.skEngineId = skEngineId
```
Comment (tkurki) [inline utils.js]:
```
module.exports = {
  chooseField,
  skEngineId
}
```
would be my preference here.

Comment (sbender9) [reply utils.js]: fixed
